network:
  name: dinov2
  model: openood/networks/dinov2.py
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: True          # set 'True' to load pretrained model
  num_gpus: '@{num_gpus}'
dataset:
  image_size: 384
ood_dataset:
  image_size: 384
