dataset:
  name: cub200
  num_classes: 200
  pre_size: 32
  image_size: 32

  interpolation: bilinear
  normalization_type: cifar10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cub200/train_cub200.txt
    batch_size: 128
    shuffle: True
  # val:
  #   dataset_class: ImglistDataset
  #   data_dir: ./data/images_classic/
  #   imglist_pth: ./data/benchmark_imglist/cub200/val_cub200.txt
  #   batch_size: 200
  #   shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cub200/test_cub200.txt
    batch_size: 200
    shuffle: False
